name: "BCO Core"
description: "BCO platform docker image"
url: "https://www.openbase.org"
version: dev
slug: "bco-core"
arch:
  - aarch64
  - amd64
startup: application
ports:
  13781/tcp: 13781
image: openbaseorg/bco
environment:
  BCO_OPTIONS: "--host local-bco-middleware --port 13780"
