name: "BCO UI"
description: "BCO UI Webapp"
url: "https://basecubeone.org/docs/user/howto/setup-docker#deploy-the-bco-webapp-docker"
version: latest
slug: "bco-ui"
arch:
  - aarch64
  - amd64
startup: application
ports:
  80/tcp: 80
image: opaal/bco-ui-albiorix
